Add tests true continuum
igmhub/picca pull request #877
Opened 2022-04-08 10:01 UTC by cramirezpe

Added true continuum tests (test data not yet shared as it contains desi mock data).

2022-04-08 11:10 UTC, iprafols requested changes
There are some things that need changing, note that I added the "same here" comment where I had already added a related comment before not to repeat too much text. Please double check that I did not miss any of such repetitions

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        data_dir = Path(__file__).parent / "data"
use variable `THIS_DIR` to access the directories. Not sure where the path is, but you could define another variable similar to `THIS_DIR` at the top that points to the right place

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        var_lss = expected_flux.get_var_lss(10**Forest.log_lambda_grid)[:-1]
I would get the `log_lambda_grid` from the test file. This way if we change the default values for this variable (in `setup_forest`) the test will still work

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        var_lss = expected_flux.get_var_lss(10**Forest.log_lambda_grid)[:-1]
Also this means we can drop the `Forest` import at the top

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        log_lambda_ = np.arange(3.5563025007672873, 3.7403626894942437, 0.0003)
rename to `log_lambda`

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        data_dir = Path(__file__).parent / "data"
same here

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        data_dir = Path(__file__).parent / "data"
same here

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +            if "REPLACE_TEST_VALUES" in os.environ and os.environ["REPLACE_TEST_VALUES"] == "Y":
I would not add this copying thing here. The point of manually copying the files when we really need to update the test suite is to make sure we don't do it automatically by mistake (e.g. if the environment variable was set for some other reason)

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +            if "REPLACE_TEST_VALUES" in os.environ and os.environ["REPLACE_TEST_VALUES"] == "Y":
same here

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        """Test method compute_mean_cont_lin for class TrueContinuum"""
the method is called `compute_mean_cont`

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        data_dir = Path(__file__).parent / "data"
same here

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        if "REPLACE_TEST_VALUES" in os.environ and os.environ["REPLACE_TEST_VALUES"] == "Y":
same here

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        """Test method compute_mean_cont_log for class TrueContinuum"""
same here

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        data_dir = Path(__file__).parent / "data"
same here

2022-04-08 11:10 UTC, iprafols commented on py/picca/tests/delta_extraction/expected_flux_tests.py
> +        if "REPLACE_TEST_VALUES" in os.environ and os.environ["REPLACE_TEST_VALUES"] == "Y":
same here

2022-04-22 07:58 UTC, cramirezpe commented
@iprafols I think we can already merge this. Is there anything I need to do before?

2022-04-25 09:07 UTC, iprafols approved these changes

2022-04-25 09:07 UTC, merged